// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnVtSztDRODcgFJPqyZRpb5lz4kLk_kGY',
    appId: '1:751464433777:web:bd49a472707fb06ecfb3d0',
    messagingSenderId: '751464433777',
    projectId: 'relay-app-32289',
    authDomain: 'relay-app-32289.firebaseapp.com',
    storageBucket: 'relay-app-32289.firebasestorage.app',
    measurementId: 'G-2GP2DSZ5Q4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcshKNenbXJZB31wBalHlnItuc15rNWUY',
    appId: '1:751464433777:android:d0d7a2b3f195c1ffcfb3d0',
    messagingSenderId: '751464433777',
    projectId: 'relay-app-32289',
    storageBucket: 'relay-app-32289.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVYQ2_AtKJcKqQ4iDCZ8Es3tGvBerZ_bE',
    appId: '1:751464433777:ios:1bca299c33c7f2e2cfb3d0',
    messagingSenderId: '751464433777',
    projectId: 'relay-app-32289',
    storageBucket: 'relay-app-32289.firebasestorage.app',
    iosBundleId: 'com.example.relayApp',
  );
}
